= News & Events
:toc: macro
:toclevels: 2

Stay up-to-date with the latest happenings in the Exa-MA project.

== Recent Events

* **General Assembly – January 14–15, 2025**  The Exa-MA consortium gathered at the Université de Strasbourg to review progress, welcome new team members, and discuss future directions. Highlights included updates on WP4 and WP7, along with interactive discussions about cross-work-package collaborations.  
  more details available  xref:news/2025/20250114-15-ag.adoc[> here].

* **Webinar Recap – Packaging HPC Software - Dec 3, 2025 **  E. Agullo (INRIA) led a webinar on modern packaging strategies using Spack and Guix-HPC, and J. Cladellas (UNISTRA) provided a preview of https://github.com/feelpp/benchmarking/[*feelpp.benchmarking*], a new tool for benchmarking HPC software on EuroHPC systems, see for example https://bench.feelpp.org[bench.feelpp.org] website generated using the tool for the toolboxes of Feel++

== Upcoming Events

* **SciML'25 - March 24-25-26 **   Several colleagues from the Exa-MA project are set to attend the SCIML25 conference at Politecnico di Milano. Notably, our colleague Emmanuel Franck – leader of WP2 – is invited speaker. The conference, organized by Politecnico di Milano, promises to be a stimulating forum for discussing cutting-edge research in scientific machine learning, including both academia and industry. It will provide an excellent platform for exchanging ideas on topics such as optimal transport, AI, and high-performance computing, all of which are central to our project’s objectives. For more details about the event, please visit the  https://www.mate.polimi.it/events/EMS-TAG-SciML-25/[> official website].


* **Training Session on CI/CD & Benchmarking - March 24,25,26 **   
  In collaboration with CoE Hidalgo2, we will soon host a training session focused on CI/CD best practices and advanced benchmarking for HPC software. Here is the https://events.it4i.cz/event/308/overview[training page].

* **Workshops & Seminars**  
  We have a series of upcoming workshops and seminars to foster collaboration and share advances within the Exa-MA and broader NumPEx communities. More details will be announced shortly.

== Archive

For a complete list of past events and detailed recaps, please visit our archive section on the xref:news.adoc[News & Events] page or contact us for further information.
